# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/osx-64/bzip2-1.0.8-h1de35cc_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/c-ares-1.19.1-h6c40b1e_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/ca-certificates-2023.08.22-hecd8cb5_0.conda
https://conda.anaconda.org/conda-forge/label/cf201901/osx-64/eigen-3.3.7-h2d50403_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/giflib-5.2.1-h6c40b1e_3.conda
https://conda.anaconda.org/conda-forge/label/cf201901/osx-64/gmp-6.1.2-hfc679d8_0.tar.bz2
https://conda.anaconda.org/conda-forge/label/cf201901/osx-64/icu-58.2-hfc679d8_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/jpeg-9e-h6c40b1e_1.conda
https://conda.anaconda.org/conda-forge/label/cf201901/osx-64/lame-3.100-h470a237_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/libcxx-14.0.6-h9765a3e_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/libdeflate-1.17-hb664fd8_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/libev-4.33-h9ed2024_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/libffi-3.4.4-hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/libiconv-1.16-hca72f7f_2.conda
https://repo.anaconda.com/pkgs/main/osx-64/libopus-1.3.1-h1de35cc_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/libwebp-base-1.3.2-h6c40b1e_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/llvm-openmp-14.0.6-h0dcd299_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/ncurses-6.4-hcec6c5f_0.conda
https://conda.anaconda.org/conda-forge/label/cf201901/osx-64/nettle-3.4.1-h470a237_2.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/pixman-0.40.0-h9ed2024_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/x264-1!157.20191217-h1de35cc_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/xz-5.4.2-h6c40b1e_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/yaml-0.2.5-haf1e3a3_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/zlib-1.2.13-h4dc903c_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/expat-2.5.0-hcec6c5f_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/graphite2-1.3.14-he9d5cce_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/lerc-3.0-he9d5cce_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/libedit-3.1.20221030-h6c40b1e_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/libgfortran5-11.3.0-h9dfd629_28.conda
https://repo.anaconda.com/pkgs/main/osx-64/libllvm14-14.0.6-h91fad77_3.conda
https://repo.anaconda.com/pkgs/main/osx-64/libpng-1.6.39-h6c40b1e_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/libvpx-1.7.0-h378b8a2_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/libxml2-2.10.4-h930c0e2_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/lz4-c-1.9.4-hcec6c5f_0.conda
https://conda.anaconda.org/conda-forge/label/cf201901/osx-64/mysql-5.7.20-h0a44026_1001.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/openh264-2.1.1-h8346a28_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/openssl-3.0.11-hca72f7f_2.conda
https://repo.anaconda.com/pkgs/main/osx-64/pcre-8.45-h23ab428_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/readline-8.2-hca72f7f_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/tk-8.6.12-h5d9f67b_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/freetype-2.12.1-hd8bbffd_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/gettext-0.21.0-he85b6c0_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/krb5-1.20.1-h428f121_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/libclang13-14.0.6-default_habbcc1a_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/libgfortran-5.0.0-11_3_0_hecd8cb5_28.conda
https://repo.anaconda.com/pkgs/main/osx-64/libnghttp2-1.52.0-h9beae6a_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/libssh2-1.10.0-h04015c4_2.conda
https://repo.anaconda.com/pkgs/main/osx-64/libxslt-1.1.37-h6d1eb0e_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/sqlite-3.41.2-h6c40b1e_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/zstd-1.5.5-hc035e20_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/fontconfig-2.14.1-hb0a0c50_2.conda
https://repo.anaconda.com/pkgs/main/osx-64/glib-2.69.1-hfff2838_2.conda
https://conda.anaconda.org/conda-forge/label/cf201901/osx-64/gnutls-3.6.5-ha0399c4_1.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/libclang-14.0.6-default_hd95374b_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/libcurl-8.2.1-hf20ceda_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/libopenblas-0.3.21-h54e7dc3_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/libpq-12.15-h04015c4_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/libtiff-4.5.1-hcec6c5f_0.conda
https://conda.anaconda.org/conda-forge/label/cf201901/osx-64/openblas-0.3.5-ha44fe06_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/python-3.8.18-h5ee71fb_0.conda
https://conda.anaconda.org/conda-forge/label/cf201901/osx-64/blas-1.1-openblas.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/cairo-1.16.0-h3ce6f7e_5.conda
https://repo.anaconda.com/pkgs/main/osx-64/ffmpeg-4.2.2-h97e5cf8_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/gstreamer-1.14.1-h6c40b1e_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/hdf5-1.12.1-ha01d115_3.conda
https://repo.anaconda.com/pkgs/main/osx-64/libwebp-1.3.2-hf6ce154_0.conda
https://conda.anaconda.org/conda-forge/label/cf201901/osx-64/openjpeg-2.3.0-h316dc23_3.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/pyyaml-6.0-py38h6c40b1e_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/setuptools-68.0.0-py38hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/wheel-0.41.2-py38hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/gst-plugins-base-1.14.1-hcec6c5f_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/harfbuzz-4.3.0-hffc734d_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/numpy-base-1.24.3-py38hc93c6d9_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/pip-23.2.1-py38hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/numpy-1.24.3-py38h57a7bef_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/qt-main-5.15.2-h1076e38_9.conda
https://repo.anaconda.com/pkgs/main/osx-64/qt-webengine-5.15.9-h90a370e_7.conda
https://repo.anaconda.com/pkgs/main/osx-64/qtwebkit-5.212-hbfab81c_5.conda
https://repo.anaconda.com/pkgs/main/osx-64/opencv-4.6.0-py38h9991a6c_5.conda
